version: '3'
services:
  traffic-server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
